version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
      args:
        - TZ=Asia/Tokyo
    ports:
      - 9000
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=db_01
      - DB_USERNAME=admin
      - DB_PASSWORD=mysqlryoga1
      - TZ=Asia/Tokyo

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=db_01
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=mysqlryoga1
      - MYSQL_ROOT_PASSWORD=mysqlryoga1
      - TZ=Asia/Tokyo
    ports:
      - 3306

volumes:
  db-store:

